from configparser import ConfigParser

CONFIG = ConfigParser()
CONFIG.read("config.ini")
ORDER_KAFKA_TOPIC = CONFIG["KAFKA"]["ORDER_KAFKA_TOPIC"]
ORDER_CONFIRMED_KAFKA_TOPIC = CONFIG["KAFKA"]["ORDER_CONFIRMED_KAFKA_TOPIC"]
HOST = CONFIG["KAFKA"]["HOST"]